### ISSUE TITLE
VersionInformation.txt not updated after release

### ISSUE THREAD

**Issue by pauska** [scepman/install#17]
Hi,

We're using a pipeline to pull down the latest release, based on VersionInformation.txt in the dist folder. I now see that this file hasn't been updated after the last release. Should we rely on this file to pull releases?

**Comment by bb-froggy** [comment]
Yes, it is still updated regularly, but there is some delay.

SCEPman loads this file to display an update hint on its homepage.

We have released version 2.6 here and therefore those SCEPman instances using GitHub for WEBSITE_RUN_FROM_PACKAGE will update automatically to this version (which is most of them), but if you install SCEPman from Azure Marketplace you will initially still get the 2.5 until it updates (which happens quickly, but still). Therefore, we didn't yet want to display the update notification; we don't want to display it to people who have a fresh SCEPman Marketplace installation. Because of the quick auto-update, we are usually a bit lazy about updating the Marketplace installation and therefore the delay updating the VersionInformation.txt. This happens every time.

Now that I know that there is someone who depends on it, I will make the team aware of it and we'll speed this up a bit :-).

For the current release, we'll publish it this week and update VersionInformation.txt accordingly.

**Comment by pauska** [comment]
Thanks for the explanation! We're in no rush to upgrade, I just wanted to make sure that the file gets updated at some point 👍

**Comment by pauska** [comment]
As a request - could it be possible to include a file inside the Artifact to indicate what version it is?

**Comment by bb-froggy** [comment]
You could already take the Scepman.Server.dll and check the File version. In PowerShell, you could do it this way:
```
$dll = Get-Item Scepman.Server.dll
$dll.VersionInfo.ProductVersion
```

For Certificate Master, you can likewise use CertMaster.Web.dll.

Would that work for you? This is how SCEPman and Certificate Master know their own version, too, so this is very reliable.

**Comment by pauska** [comment]
Thanks, that's an excellent fix for us as we are already using PowerShell in our pipeline.
